#!/bin/bash -e

checkReboot() {
  echo Installation will take effect after reboot!!!
}

systemctl enable rockpi-penta.service

model=$(tr -d '\0' </proc/device-tree/model)

case "$model" in
"Raspberry Pi 5"*)
  raspi-config nonint do_i2c 0 >/dev/null || true
  cp /usr/bin/rockpi-penta/env/rpi5.env /etc/rockpi-penta.env
  systemctl start rockpi-penta.service
  ;;
"Raspberry Pi 4"*)
  raspi-config nonint do_i2c 0 >/dev/null || true
  cp /usr/bin/rockpi-penta/env/rpi4.env /etc/rockpi-penta.env
  systemctl start rockpi-penta.service
  ;;
*)
  echo Not support in your board.
  exit 2
  ;;
esac
